# services.yaml
heat_on:
  description: "Turn on the volcano heat"
  fields:
    entity_id:
      description: "The ID of the volcano entity"
      example: "sensor.volcano_temperature"

heat_off:
  description: "Turn off the volcano heat"
  fields:
    entity_id:
      description: "The ID of the volcano entity"
      example: "sensor.volcano_temperature"
